#!/usr/bin/env python3
"""
Diagnose pseudo environment labels generated by KMeans
"""

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, normalized_mutual_info_score, adjusted_rand_score
from torch_geometric.loader import DataLoader

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from cag.data import infer_n_nodes, make_dataset, read_subject_records
from cag.graph import batch_subject_ids
from cag.models import CAGModel
from cag.split import external_site_split, stratified_cv_indices
from cag.train import make_model
from cag.utils import select_device


def _extract_model_state(checkpoint) -> tuple[dict, dict]:
    if not isinstance(checkpoint, dict):
        return checkpoint, {"model": {}, "training": {}}
    config = checkpoint.get("config", {"model": {}, "training": {}}) or {"model": {}, "training": {}}
    if "model_state" in checkpoint:
        return checkpoint["model_state"], config
    if "model_state_dict" in checkpoint:
        return checkpoint["model_state_dict"], config
    return checkpoint, config


def load_checkpoint(checkpoint_path: Path, device: torch.device, n_nodes: int) -> tuple[CAGModel, dict]:
    """Load model and config from checkpoint"""
    checkpoint = torch.load(checkpoint_path, map_location=device)
    state_dict, config = _extract_model_state(checkpoint)
    model_config = config.get("model", config if isinstance(config, dict) else {})
    model = make_model(n_nodes=n_nodes, config=model_config).to(device)
    try:
        model.load_state_dict(state_dict)
        config["_checkpoint_load"] = {"loaded_keys": len(state_dict), "skipped_keys": {}}
    except RuntimeError as exc:
        current_state = model.state_dict()
        compatible_state = {}
        skipped_keys = {}
        for key, value in state_dict.items():
            if key in current_state and current_state[key].shape == value.shape:
                compatible_state[key] = value
            else:
                skipped_keys[key] = {
                    "checkpoint_shape": list(value.shape) if hasattr(value, "shape") else None,
                    "model_shape": list(current_state[key].shape) if key in current_state else None,
                }
        if not compatible_state:
            raise RuntimeError(f"No compatible model parameters found in checkpoint: {checkpoint_path}") from exc
        current_state.update(compatible_state)
        model.load_state_dict(current_state)
        config["_checkpoint_load"] = {"loaded_keys": len(compatible_state), "skipped_keys": skipped_keys}
    model.eval()
    return model, config


def build_pseudo_env_labels(
    model: CAGModel,
    train_loader: DataLoader,
    n_env: int = 2,
    seed: int = 42,
    device: torch.device | None = None,
) -> tuple[dict[str, int], np.ndarray, np.ndarray, float]:
    """Build pseudo environment labels and return additional metrics"""
    model.eval()
    device = device or next(model.parameters()).device
    embeddings: list[np.ndarray] = []
    subject_ids: list[str] = []
    for batch in train_loader:
        batch = batch.to(device)
        outputs = model(batch)
        embeddings.append(outputs["emb_gc"].detach().cpu().numpy())
        subject_ids.extend(batch_subject_ids(batch))
    if not embeddings:
        return {}, np.array([]), np.array([]), 0.0
    matrix = np.concatenate(embeddings, axis=0)
    clusters = min(int(n_env), matrix.shape[0])
    if clusters <= 1:
        labels = np.zeros(matrix.shape[0], dtype=int)
        silhouette = 0.0
    else:
        labels = KMeans(n_clusters=clusters, random_state=seed, n_init=10).fit_predict(matrix)
        if len(set(labels)) > 1:
            silhouette = silhouette_score(matrix, labels)
        else:
            silhouette = 0.0
    return {str(subject_id): int(label) for subject_id, label in zip(subject_ids, labels)}, labels, matrix, float(silhouette)


def main():
    parser = argparse.ArgumentParser(description="Diagnose pseudo environment labels")
    parser.add_argument("--subjects_csv", type=Path, required=True, help="Path to subjects CSV")
    parser.add_argument("--fc_dir", type=Path, required=True, help="Path to functional connectivity directory")
    parser.add_argument("--checkpoint", type=Path, required=True, help="Path to model checkpoint")
    parser.add_argument("--test_site", type=str, required=True, help="Test site name")
    parser.add_argument("--fold", type=int, default=1, help="Fold index")
    parser.add_argument("--out_dir", "--output_dir", dest="out_dir", type=Path, default=Path("outputs/diagnostics/pseudo_env"), help="Output directory")
    parser.add_argument("--device", type=str, default="auto", help="Device: auto, cpu, cuda, or cuda:N")
    args = parser.parse_args()

    output_dir = args.out_dir / f"{args.test_site}/fold_{args.fold:02d}"
    output_dir.mkdir(parents=True, exist_ok=True)

    records = read_subject_records(args.subjects_csv, args.fc_dir)
    n_nodes = infer_n_nodes(records)

    device = select_device(args.device)
    model, config = load_checkpoint(args.checkpoint, device, n_nodes)
    training_config = config.get("training", {}) if isinstance(config, dict) else {}
    model_config = config.get("model", {}) if isinstance(config, dict) else {}

    base_train_indices, test_indices = external_site_split(records, test_site=args.test_site)
    folds = stratified_cv_indices(
        records=records,
        candidate_indices=base_train_indices,
        n_splits=int(training_config.get("n_splits", 10)),
        seed=int(training_config.get("seed", 42)),
    )
    if args.fold < 1 or args.fold > len(folds):
        raise ValueError(f"--fold must be in [1, {len(folds)}], got {args.fold}")
    train_indices, val_indices = folds[args.fold - 1]

    train_dataset = make_dataset(records, train_indices)
    pseudo_loader = DataLoader(
        train_dataset,
        batch_size=int(training_config.get("batch_size", 32)),
        shuffle=False,
        num_workers=int(training_config.get("num_workers", 0)),
    )

    pseudo_env, labels, embeddings, silhouette = build_pseudo_env_labels(
        model=model,
        train_loader=pseudo_loader,
        n_env=int(model_config.get("n_env", 2)),
        seed=int(training_config.get("seed", 42)),
        device=device,
    )

    results = {
        "test_site": args.test_site,
        "fold": args.fold,
        "checkpoint": str(args.checkpoint),
        "checkpoint_load": config.get("_checkpoint_load", {}) if isinstance(config, dict) else {},
    }

    unique, counts = np.unique(labels, return_counts=True)
    cluster_counts = {int(k): int(v) for k, v in zip(unique, counts)}
    results["cluster_counts"] = cluster_counts
    results["silhouette"] = silhouette

    train_records = [records[i] for i in train_indices]
    true_sites = [r.site for r in train_records]
    true_y = [r.label for r in train_records]

    site_to_int = {site: i for i, site in enumerate(sorted(set(true_sites)))} if true_sites else {}
    true_site_int = [site_to_int.get(s, 0) for s in true_sites]

    if len(set(true_site_int)) > 1 and len(set(labels)) > 1:
        results["pseudo_env_vs_site_NMI"] = float(normalized_mutual_info_score(true_site_int, labels))
        results["pseudo_env_vs_site_ARI"] = float(adjusted_rand_score(true_site_int, labels))
    else:
        results["pseudo_env_vs_site_NMI"] = 0.0
        results["pseudo_env_vs_site_ARI"] = 0.0

    if len(set(true_y)) > 1 and len(set(labels)) > 1:
        results["pseudo_env_vs_y_NMI"] = float(normalized_mutual_info_score(true_y, labels))
        results["pseudo_env_vs_y_ARI"] = float(adjusted_rand_score(true_y, labels))
    else:
        results["pseudo_env_vs_y_NMI"] = 0.0
        results["pseudo_env_vs_y_ARI"] = 0.0

    cluster_asd_tdc = {}
    for cluster in unique:
        cluster_mask = labels == cluster
        cluster_y = np.array(true_y)[cluster_mask]
        asd_count = int(np.sum(cluster_y == 1))
        tdc_count = int(np.sum(cluster_y == 0))
        cluster_asd_tdc[int(cluster)] = {"ASD": asd_count, "TDC": tdc_count}
    results["cluster_asd_tdc"] = cluster_asd_tdc

    cluster_site_dist = {}
    for cluster in unique:
        cluster_mask = labels == cluster
        cluster_sites = np.array(true_sites)[cluster_mask]
        site_counts = {}
        for site in set(cluster_sites):
            site_counts[site] = int(np.sum(cluster_sites == site))
        cluster_site_dist[int(cluster)] = site_counts
    results["cluster_site_distribution"] = cluster_site_dist

    with (output_dir / "diagnostics.json").open("w", encoding="utf-8") as f:
        json.dump(results, f, indent=2)

    detailed_data = []
    for record, label in zip(train_records, labels):
        detailed_data.append({
            "subject_id": record.subject_id,
            "pseudo_env_label": int(label),
            "true_y": record.label,
            "true_site": record.site,
        })
    pd.DataFrame(detailed_data).to_csv(output_dir / "detailed.csv", index=False)

    print(json.dumps(results, indent=2))


if __name__ == "__main__":
    main()
